include $(RIOTBOARD)/atmega1284p/Makefile.include

# configure the terminal program
PORT_LINUX          ?= $(firstword $(sort $(wildcard /dev/ttyUSB*)))

# flash tool configuration
OFLAGS = -j .text -j .data -O ihex


# JTAG ICE mkII
FLASHER = avrdude
AVRDUDE_PROGRAMMER = jtag2isp
FFLAGS =  -p m1284p -P usb -u 

# INCLUDES += -I$(RIOTBOARD)/atmega1284p/include

