include $(RIOTBOARD)/atmega1284p/Makefile.include

# configure the terminal program
PORT_LINUX          ?= $(firstword $(sort $(wildcard /dev/ttyUSB*)))

# flash tool configuration
OFLAGS = -j .text -j .data -O ihex

FLASHER = avrdude
PROGRAMMER = jtag2isp
# JTAG ICE mkII
FFLAGS_EXTRA =  usb -u 

# INCLUDES += -I$(RIOTBOARD)/atmega1284p/include
