#ifndef ATMEGA_PCINT_H
#define ATMEGA_PCINT_H
#define ATMEGA_PCINT_MAP_PCINT0 { GPIO_PIN(0, 0), GPIO_PIN(0, 1), GPIO_PIN(0, 2), GPIO_PIN(0, 3), GPIO_PIN(0, 4), GPIO_PIN(0, 5), GPIO_PIN(0, 6), GPIO_PIN(0, 7) }
#define ATMEGA_PCINT_MAP_PCINT1 { GPIO_PIN(1, 0), GPIO_PIN(1, 1), GPIO_PIN(1, 2), GPIO_PIN(1, 3), GPIO_PIN(1, 4), GPIO_PIN(1, 5), GPIO_PIN(1, 6), GPIO_PIN(1, 7) }
#define ATMEGA_PCINT_MAP_PCINT2 { GPIO_PIN(2, 0), GPIO_PIN(2, 1), GPIO_PIN(2, 2), GPIO_PIN(2, 3), GPIO_PIN(2, 4), GPIO_PIN(2, 5), GPIO_PIN(2, 6), GPIO_PIN(2, 7) }
#define ATMEGA_PCINT_MAP_PCINT3 { GPIO_PIN(3, 0), GPIO_PIN(3, 1), GPIO_PIN(3, 2), GPIO_PIN(3, 3), GPIO_PIN(3, 4), GPIO_PIN(3, 5), GPIO_PIN(3, 6), GPIO_PIN(3, 7) }
#endif