CPU = atmega1284p

FEATURES_PROVIDED += periph_adc
FEATURES_PROVIDED += periph_gpio periph_gpio_irq
FEATURES_PROVIDED += periph_i2c
FEATURES_PROVIDED += periph_pwm
FEATURES_PROVIDED += periph_spi
FEATURES_PROVIDED += periph_timer
FEATURES_PROVIDED += periph_uart

FEATURES_PROVIDED += adxl345

# The board MPU family (used for grouping by the CI system) from inga_common
FEATURES_MCU_GROUP = avr8


