# configure the terminal program
PORT_LINUX          ?= $(firstword $(sort $(wildcard /dev/ttyUSB*)))
PORT_DARWIN         ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
BAUD                ?= 9600
ATMEGA328P_CLOCK    ?=
include $(RIOTMAKE)/tools/serial.inc.mk
# USEMODULE += boards_common_inga

ifneq (,$(ATMEGA1284P_CLOCK))
  CFLAGS += -DCLOCK_CORECLOCK=$(ATMEGA1284P_CLOCK)
endif

# flash tool configuration
export OFLAGS = -j .text -j .data -O ihex

# New flash tool
include $(RIOTMAKE)/tools/inga_tool.inc.mk

#export INCLUDES += -I$(RIOTBOARD)/common/inga/include/

# setup the boards dependencies
include $(RIOTBOARD)/$(BOARD)/Makefile.dep

include $(RIOTCPU)/$(CPU)/Makefile.dep
include $(RIOTBOARD)/common/atmega/Makefile.include
#include $(RIOTBOARD)/common/inga/Makefile.include


