include $(RIOTBOARD)/common/inga/Makefile.dep

ifneq (,$(filter netdev_default gnrc_netdev_default,$(USEMODULE)))
  USEMODULE += at86rf233
endif

ifneq (,$(filter idealvolting,$(USEMODULE)))
  FEATURES_REQUIRED += periph_i2c_slave periph_rtt
  USEMODULE += max541x
endif