# configure the terminal program
PORT_LINUX  ?= /dev/ttyUSB0
PORT_DARWIN ?= $(firstword $(sort $(wildcard /dev/tty.usbmodem*)))
# refine serial port information for pyterm
BAUD        ?= 115200

export FLASHER = avrdude
export AVRDUDE_PROGRAMMER = jtag2isp 


include $(RIOTBOARD)/common/atmega/Makefile.include
